version: 2
jobs:
  go_test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          command: go mod download
      - save_cache:
          key: v1-pkg-cache
          paths:
            - '/go/pkg'
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - run: grep -v main.go coverage.txt > coverage.txt.fixed
      - run: mv coverage.txt.fixed coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)
  go_lint:
    docker:
    - image: golangci/golangci-lint:v1.23.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          command: go mod tidy && git --no-pager diff --stat go.*
      - run:
          command: go mod download
      - save_cache:
          key: v1-pkg-cache
          paths:
            - '/go/pkg'
      - run: golangci-lint run

workflows:
  version: 2
  all_test:
    jobs:
      - go_test
      - go_lint
